elasticsearch:
  build: elasticsearch/
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./elasticsearch/d4c_scripts:/usr/share/elasticsearch/d4c_scripts
    - ./elasticsearch/config:/usr/share/elasticsearch/config
    - ./elasticsearch/sgconfig:/usr/share/elasticsearch/plugins/search-guard-2/sgconfig
    - /encrypted_1/ubuntu/data/elk/elastic:/usr/share/elasticsearch/data
logstash:
  image: logstash:2.3.4-1
  command: logstash -f /etc/logstash/conf.d/logstash.conf -v
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /encrypted_1/ubuntu/data/elk-test/tls/:/etc/pki/tls/
  ports:
    - "5044:5044"
    - "15044:15044"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
