FROM elasticsearch:2.3.3

RUN /usr/share/elasticsearch/bin/plugin install --batch com.floragunn/search-guard-ssl/2.3.3.13
RUN /usr/share/elasticsearch/bin/plugin install --batch com.floragunn/search-guard-2/2.3.3.2
RUN /usr/share/elasticsearch/bin/plugin install --batch cloud-aws
